### DISCUSSION TITLE
How can I activate the "Heizstab" via Register? Best practive for PV + WPM ?

### DISCUSSION THREAD

**Discussion by JulianPSLearner** [pail23/stiebel_eltron_isg_component#292] [Q&A]
Hi everyone,

I recently installed a photovoltaic system on my roof. Whenever I have excess energy production, I’d like to activate my immersion heater (Heizstab) to increase the water buffer storage temperature. However, I haven’t been able to find a Modbus register to control this.

What’s the best way to increase the water buffer storage temperature when the sun is shining?

Do I need to manually set the target temperature (SOLL-Wert) to, say, 65°C when there’s excess energy and then lower it back to 40°C once the overproduction ends?

Thanks for your help!

**Comment by DaZeller** [comment]
Hi Julian, 

I have a LWZ8CS Premium and I've activated "SG ready" in the ISG. With ISG-Menu Settings / Energy management / SG-Ready input set to "ModBus" (ISG-Web interface / Einstellungen / Energiemanagement / SG-Ready Eingang) I created an Automation to set SG-Ready Input 1 when exess energy is available. In the above mentioned Menu you can also set a "higher" target temperature for HK and seperatly for warm water in case SG-Ready is active.

BR Michael

**Reply by JulianPSLearner** [reply]
Hi DaZeller,

I have a Switch called switch.stiebel_eltron_isg_sg_ready_input_1

Whenever I have overproduction I have a boolean value that turns on an goes "overproduction active". Then I have an Automation that switches SGReady on. Therefore the heating Profile in the Energy section goes active. When the boolean variable turns Off, the Automation Sets SGReady to 0.

Ist this correct? Is this the proper way?

I Just realized I have two SG ready  Inputs. For what is the second one?

BR Julian

**Reply by DaZeller** [reply]
Hi Julian,

I have the "SG-Ready On" always on "ON". I just toggle the SG-Ready 1 or 2 depending on how much over-production my PV delivers. With SG-Ready 1 and 2 you could set two stages of energy optimization. As far as I understood the SG1 targets can be defined in Settings / Energymanagement and SG2 is always 65°C (but here I'm not sure).
Documentation from Stiebel Eltron to the provided possibilities with SG-ready is quite poor (at least what I could find).

My Automations look like this:

```
alias: SG-Ready-1-EIN
description: Einschalten von SG-Ready1 wenn eHZ1 für 15 Minuten unter -2000W
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.ehz1_leistung_w
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: -1000
condition:
  - condition: numeric_state
    entity_id: sensor.lwz8_actual_temperature_water
    below: 50
action:
  - type: turn_on
    device_id: 7b03b317d6271fec27d9e1de2642593d
    entity_id: 34f98de2638f968e25846179b351684e
    domain: switch
mode: single

alias: SG-Ready2-EIN
description: Einschalten von SG-Ready2 wenn eHZ1 für 15 Minuten unter -3000W
trigger:
  - platform: numeric_state
    entity_id: sensor.ehz1_leistung_w
    for:
      hours: 0
      minutes: 15
      seconds: 0
    below: -3000
condition:
  - condition: numeric_state
    entity_id: sensor.energy_production_today_remaining
    above: 1
    value_template: ""
    enabled: false
  - condition: numeric_state
    entity_id: sensor.lwz8_actual_temperature_water
    below: 50
action:
  - type: turn_on
    device_id: 7b03b317d6271fec27d9e1de2642593d
    entity_id: e9333f6f7440ef42c3fd93f9ea11285d
    domain: switch
  - type: turn_on
    device_id: 7b03b317d6271fec27d9e1de2642593d
    entity_id: 34f98de2638f968e25846179b351684e
    domain: switch
mode: single

alias: SG-Ready-AUS
description: Ausschalten von SG-Ready1+2 wenn eHZ1 für 5 Minuten über -150W
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.ehz1_leistung_w
    for:
      hours: 0
      minutes: 10
      seconds: 0
    above: -50
condition: []
action:
  - type: turn_off
    device_id: 7b03b317d6271fec27d9e1de2642593d
    entity_id: 34f98de2638f968e25846179b351684e
    domain: switch
  - type: turn_off
    device_id: 7b03b317d6271fec27d9e1de2642593d
    entity_id: e9333f6f7440ef42c3fd93f9ea11285d
    domain: switch
mode: single
```

I'd appreciate constructive feedback to the automations.

BR Michael

**Reply by JulianDVLABS** [reply]
> Hi Julian,
> 
> I have the "SG-Ready On" always on "ON". I just toggle the SG-Ready 1 or 2 depending on how much over-production my PV delivers. With SG-Ready 1 and 2 you could set two stages of energy optimization. As far as I understood the SG1 targets can be defined in Settings / Energymanagement and SG2 is always 65°C (but here I'm not sure). Documentation from Stiebel Eltron to the provided possibilities with SG-ready is quite poor (at least what I could find).
> 
> My Automations look like this:
> 
> ```
> alias: SG-Ready-1-EIN
> description: Einschalten von SG-Ready1 wenn eHZ1 für 15 Minuten unter -2000W
> trigger:
>   - platform: numeric_state
>     entity_id:
>       - sensor.ehz1_leistung_w
>     for:
>       hours: 0
>       minutes: 5
>       seconds: 0
>     below: -1000
> condition:
>   - condition: numeric_state
>     entity_id: sensor.lwz8_actual_temperature_water
>     below: 50
> action:
>   - type: turn_on
>     device_id: 7b03b317d6271fec27d9e1de2642593d
>     entity_id: 34f98de2638f968e25846179b351684e
>     domain: switch
> mode: single
> 
> alias: SG-Ready2-EIN
> description: Einschalten von SG-Ready2 wenn eHZ1 für 15 Minuten unter -3000W
> trigger:
>   - platform: numeric_state
>     entity_id: sensor.ehz1_leistung_w
>     for:
>       hours: 0
>       minutes: 15
>       seconds: 0
>     below: -3000
> condition:
>   - condition: numeric_state
>     entity_id: sensor.energy_production_today_remaining
>     above: 1
>     value_template: ""
>     enabled: false
>   - condition: numeric_state
>     entity_id: sensor.lwz8_actual_temperature_water
>     below: 50
> action:
>   - type: turn_on
>     device_id: 7b03b317d6271fec27d9e1de2642593d
>     entity_id: e9333f6f7440ef42c3fd93f9ea11285d
>     domain: switch
>   - type: turn_on
>     device_id: 7b03b317d6271fec27d9e1de2642593d
>     entity_id: 34f98de2638f968e25846179b351684e
>     domain: switch
> mode: single
> 
> alias: SG-Ready-AUS
> description: Ausschalten von SG-Ready1+2 wenn eHZ1 für 5 Minuten über -150W
> trigger:
>   - platform: numeric_state
>     entity_id:
>       - sensor.ehz1_leistung_w
>     for:
>       hours: 0
>       minutes: 10
>       seconds: 0
>     above: -50
> condition: []
> action:
>   - type: turn_off
>     device_id: 7b03b317d6271fec27d9e1de2642593d
>     entity_id: 34f98de2638f968e25846179b351684e
>     domain: switch
>   - type: turn_off
>     device_id: 7b03b317d6271fec27d9e1de2642593d
>     entity_id: e9333f6f7440ef42c3fd93f9ea11285d
>     domain: switch
> mode: single
> ```
> 
> I'd appreciate constructive feedback to the automations.
> 
> BR Michael

Hi Michael,

Long time no see! :-) I was wondering if I could get your feedback on something.

Right now, my SG1 is set to kick in whenever there’s excess energy, but only if it exceeds 2,500 Watts. It’s a bit frustrating when I have, say, 2,200 Watts available all day, but the automation doesn’t trigger because it hasn't hit that threshold.

I’ve found out that many people are adding an immersion heater (Heizstab) directly into the water tank. Apparently, these can dynamically adjust their power consumption based on the available surplus. So, if there’s only 400 Watts of excess energy, it uses exactly that to heat the buffer tank.

This sounds really interesting to me, especially since I'm annoyed that I can't currently trigger my setup manually or adjust the power gradually. Do you have any thoughts or ideas on this?

**Comment by JulianPSLearner** [comment]
Hi Michael,

I built my automation similar to yours, or rather, I copied it. I only outsourced the detection of when there's an overproduction of electricity to a threshold helper. This way, I can more easily determine later when overproduction occurred. I plan to create an Apex Chart for tracking to correlate the electricity generation with the threshold helper. This will allow me to visually see right away if SG1 has been triggered and if the temperature has changed accordingly. What annoys me the most is that I accidentally activated the SG1 input a year ago. As a result, my heating system was probably constantly targeting the energy management temperature values, meaning 23°C for the rooms. This happened in winter. I kept wondering why my rooms were slightly warmer than what the thermostat was set to. Thanks for the help and your automation. Once I’ve tested it over the next 1-2 weeks, I’ll be happy to provide feedback. For testing purposes, I’ve also included notifications to get a feel for it. Have you made any other types of optimizations?

BR Julian

**Reply by JulianPSLearner** [reply]
Here is my automation. Feedback to yours: You have a condition that checks if the Kessel is below 50. And only then it switches on SG1. Seems a little high. I went for 45. In my Energy Dashboard I only can choose 55C° as max temp. So it seemed 45 is more reasonable.

Feedback for my automation welcome. 
```
alias: SG-Ready-1 einschalten - Heizung und PV
description: >-
  Der SG-Input 1 wird auf der Heizung eingeschalten, damit wird Überproduktion
  an Energie genutzt um den Kessel aufzuheizen. 
trigger:
  - platform: state
    entity_id:
      - binary_sensor.photovoltaik_ueberproduktion_aktiv
    to: "on"
    for:
      hours: 0
      minutes: 10
      seconds: 0
condition:
  - condition: numeric_state
    entity_id: sensor.stiebel_eltron_isg_actual_temperature_water
    below: 45
action:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.stiebel_eltron_isg_sg_ready_input_1
  - action: notify.mobile_app_pixel_6
    metadata: {}
    data:
      message: PV Energie ausreichend, Kessel wird aufgeheizt.
      data:
        color: "#00ddff"
        notification_icon: mdi:solar-power-variant-outline
        visibility: public
mode: single

```
