### ISSUE TITLE
power usage of cooling

### ISSUE THREAD

**Issue by ranzigepad** [pail23/stiebel_eltron_isg_component#394]
Heating power usage is supported directly, but power usage of cooling isn't

please add a counter for the value "INVERTER POWER" when cooling is on (true/on)
Now it seems the heatpump's isn't using power in the summer, but is does.

**Comment by tommolling** [comment]
Yes, I own a LWZ8 CS and it would we really useful to see these values.

**Comment by Padanian** [comment]
I've been asking to publish cooling registers forever. not much success.

**Comment by tommolling** [comment]
Would this be helpful to find the modbus registers?
https://www.stiebel-eltron.ch/content/dam/ste/ch/de/downloads/kundenservice/smart-home/Modbus/Modbus%20Bedienungsanleitung.pdf

**Comment by jahallam** [comment]
I had a look and it doesn't appear where I would have expected it to.
Page 30, section 4 has all the energy data for hot water and heating, but cooling isn't on the list.
The only entry for cooling is the time running.

<img width="716" height="428" alt="Image" src="https://github.com/user-attachments/assets/f775d57c-241b-46b2-ac42-f09fc53f3797" />

This document looks to be for WPM units, I have a WPL-25ACS. Is the modbus the same?

**Comment by jahallam** [comment]
Hi - My model is set up in English, do you think the the German code will work or will I need to adjust?

**Comment by Oliver3012** [comment]
Just changed it to english, should work as aspected:

``` yaml

rest:
  - resource: "http://YOUR-IP/?s=1,8" # **PUT YOUR LOCAL SERVICEWELT-IP RIGHT HERE**
    scan_interval: 300
    sensor:
      # ------- POWER CONSUMPTION -------
      # COOLING 1–12 M (electrical)
      - name: "HP Coolingpower 1-12M (raw)"
        value_template: >
          {% set m = value
            | regex_findall('POWER CONSUMPTION[\\s\\S]*?COOLING\\s*1[–-]12\\s*M</td>\\s*<td class="value">\\s*([0-9\\.,]+)\\s*(kWh|MWh)\\s*</td>') %}
          {% if m and m[0] %}{{ m[0][0] ~ ' ' ~ m[0][1] }}{% else %}unavailable{% endif %}

      # COOLING 1–24 h (electrical, daily value)
      - name: "HP Coolingpower 1-24h (raw)"
        value_template: >
          {% set m = value
            | regex_findall('POWER CONSUMPTION[\\s\\S]*?COOLING\\s*1[–-]24\\s*h</td>\\s*<td class="value">\\s*([0-9\\.,]+)\\s*(kWh|MWh)\\s*</td>') %}
          {% if m and m[0] %}{{ m[0][0] ~ ' ' ~ m[0][1] }}{% else %}unavailable{% endif %}

      # ------- AMOUNT OF HEAT -------
      # COOLING 1–12 M (thermal)
      - name: "HP Coolingamount 1-12M (raw)"
        value_template: >
          {% set m = value
            | regex_findall('AMOUNT OF HEAT[\\s\\S]*?COOLING\\s*1[–-]12\\s*M</td>\\s*<td class="value">\\s*([0-9\\.,]+)\\s*(kWh|MWh)\\s*</td>') %}
          {% if m and m[0] %}{{ m[0][0] ~ ' ' ~ m[0][1] }}{% else %}unavailable{% endif %}

      # COOLING 1–24 h (thermal, daily value)
      - name: "HP Coolingamount 1-24h (raw)"
        value_template: >
          {% set m = value
            | regex_findall('AMOUNT OF HEAT[\\s\\S]*?COOLING\\s*1[–-]24\\s*h</td>\\s*<td class="value">\\s*([0-9\\.,]+)\\s*(kWh|MWh)\\s*</td>') %}
          {% if m and m[0] %}{{ m[0][0] ~ ' ' ~ m[0][1] }}{% else %}unavailable{% endif %}

```

``` yaml


- sensor:
    - name: "Heatpump Coolingpower 1-12M"
      unique_id: hp_coolingpower_1_12m
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
      state: >
        {% set val = states('sensor.hp_coolingpower_1_12m_raw') %}
        {% if 'MWh' in val %}
          {{ (val | replace(' MWh','') | replace(',','.') | float * 1000) | round(0) }}
        {% elif 'kWh' in val %}
          {{ (val | replace(' kWh','') | replace(',','.') | float) | round(0) }}
        {% else %} unknown {% endif %}
  
    - name: "Heatpump Coolingpower 1-24h"
      unique_id: hp_coolingpower_1_24h
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total
      state: >
        {% set val = states('sensor.hp_coolingpower_1_24h_raw') %}
        {% if 'MWh' in val %}
          {{ (val | replace(' MWh','') | replace(',','.') | float * 1000) | round(0) }}
        {% elif 'kWh' in val %}
          {{ (val | replace(' kWh','') | replace(',','.') | float) | round(0) }}
        {% else %} unknown {% endif %}
  
    - name: "Heatpump Coolingamount 1-12M"
      unique_id: hp_coolingamount_1_12m
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
      state: >
        {% set val = states('sensor.hp_coolingamount_1_12m_raw') %}
        {% if 'MWh' in val %}
          {{ (val | replace(' MWh','') | replace(',','.') | float * 1000) | round(0) }}
        {% elif 'kWh' in val %}
          {{ (val | replace(' kWh','') | replace(',','.') | float) | round(0) }}
        {% else %} unknown {% endif %}
  
    - name: "Heatpump Coolingamount 1-24h"
      unique_id: hp_coolingamount_1_24h
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total
      state: >
        {% set val = states('sensor.hp_coolingamount_1_24h_raw') %}
        {% if 'MWh' in val %}
          {{ (val | replace(' MWh','') | replace(',','.') | float * 1000) | round(0) }}
        {% elif 'kWh' in val %}
          {{ (val | replace(' kWh','') | replace(',','.') | float) | round(0) }}
        {% else %} unknown {% endif %}

```

**Comment by Oliver3012** [comment]
The "rest:" code has to be on first level (no indentation).
``` yaml
rest: #firstlevel
  - resource: 
  ...
    sensor:
    - name: 

```
The "sensor:" code should go in "template:" section:
``` yaml
template: #firstlevel
  - sensor:
    - name:
```
