### ISSUE TITLE
[FEATURE] Add some more Sensors for WPE expansion module

### ISSUE THREAD

**Issue by piersdd** [pail23/stiebel_eltron_isg_component#89]
Our Stiebel Eltron has a WPE expansion module, providing an additional three heating circuits. 

The ISG web interface shows the following system software.
WPE;
- SOFTWARE 503
- Software version 3
ISG;
- Major version 12
- Minor version 2
- Revision 2
- Build 246

Regrettably I have no idea how to code this, but would obviously, gladly assist and test as necessary.

We're running your excellent 2023.6.0 component on Home Assistant Core 2023.7

thanks in advance,
Piers

**Comment by pail23** [comment]
@piersdd I did not find any registers related to the expansion module in the [modbus documentation](https://www.stiebel-eltron.ch/content/dam/ste/ch/de/downloads/kundenservice/smart-home/Modbus/Modbus%20Bedienungsanleitung.pdf)

Do you have any idea on which modbus registers to pick?

**Comment by piersdd** [comment]
No, the documentation does not very promising.

**Comment by netmikey** [comment]
I have a newer Heatpump that comes with 3 heating circuits built-in, so I'm currently missing the third one.

I found register listings for heating circuits 3-5 here, on Pages 6 and 7 : https://www.stiebel-eltron.de/content/dam/ste/cdbassets/historic/bedienungs-_u_installationsanleitungen/ISG_Modbus__ed049b5c-79e9-4efa-a99c-7532a657e54a.pdf

I tested register `592 ISTTEMPERATUR Raumtemperatur Heizkreis 3` using the modbus integration and it is returning the correct current temperature for my heating circuit (Heizkreis / HK) 3.

Could you please extend your integration for the additional heating circuits?

**Comment by pail23** [comment]
I have added the actual temperature and the target temperature for HK 3 in the release 2023.10. Could you please test with the latest release. I can't test it since I don't have a HK 3.

**Comment by netmikey** [comment]
@pail23 I can confirm it works, awesome!

![Screen Shot 2023-10-10 at 23 22 55](https://github.com/pail23/stiebel_eltron_isg_component/assets/1180845/57d1feb3-12e5-42b7-9093-71e610611985)
![Screen Shot 2023-10-10 at 23 23 10](https://github.com/pail23/stiebel_eltron_isg_component/assets/1180845/43367511-d5f5-4de4-9b9b-56609e9dfbda)

Any chance you could add the current room temperatures for HKs 1-3? Currently, I have to add the modbus extension to read these, it'd be nice if the Stiebel Eltron integration could provide them...

Here's my config:

```
      - name: Room Temperature HK 1
        unique_id: room_temp_hk1
        address: 583 #584 - 1
        slave: 1
        input_type: input
        unit_of_measurement: °C
        device_class: temperature
        state_class: measurement
        scale: 0.1
        precision: 1
      - name: Room Temperature HK 2
        unique_id: room_temp_hk2
        address: 587 #588 - 1
        slave: 1
        input_type: input
        unit_of_measurement: °C
        device_class: temperature
        state_class: measurement
        scale: 0.1
        precision: 1
      - name: Room Temperature HK 3
        unique_id: room_temp_hk3
        address: 591 #592 - 1
        slave: 1
        input_type: input
        unit_of_measurement: °C
        device_class: temperature
        state_class: measurement
        scale: 0.1
        precision: 1
```

**Comment by kroebler** [comment]
Same result. Great work.
I would appreciate "Pump HK 3" too.

**Comment by pail23** [comment]
@netmikey What is your modbus config for Pump HK 3?

**Comment by netmikey** [comment]
@pail23 I wanted to have the Actual and Target temperatures for HK 3 in addition to the Pump status. Since documentation about these values for HK 3 was nowhere to be found from Stiebel Eltron, I went ahead and wrote a small script to scan the bus, looking for the appropriate target values currently displayed on the ISG's web interface.

Long story short, here's the configuration for those as well:

```
    sensors:
      - name: Actual Temperature HK 3
        unique_id: actual_temp_hk3
        address: 609 #610 - 1
        slave: 1
        input_type: input
        unit_of_measurement: °C
        device_class: temperature
        state_class: measurement
        scale: 0.1
        precision: 1
      - name: Target Temperature HK 3
        unique_id: target_temp_hk3
        address: 610 #611 - 1
        slave: 1
        input_type: input
        unit_of_measurement: °C
        device_class: temperature
        state_class: measurement
        scale: 0.1
        precision: 1
```
